#' Environment to record active db packages
dbp_env <- new.env(parent = emptyenv())

#' Prepare package files based on a database connection
#'
#' @description
#' Creates a folder under dbpkgr/, writing functions and roxygen docstrings.
#' Intended to be ready to be turned into a package with [dbp_load()].
#'
#' [dbp_package()] is the one-line way to get a package as the connection
#' interface up and running. However, as the automatically generated
#' documentation is quite limited, [dbp_init()] is provided to generate the
#' files without installing the package. Then you can make your own changes
#' to the package like adding more detailed roxygen documentation.
#' Once you're done,
#' you can pass the package name to [dbp_load()] to install and load
#' the package.
#'
#' @param connection
#' A database connection object.
#'
#' @param package_name
#' A string to be used as the name of the temp package and the prefix to its
#' functions. Must be a valid package name; lowercase no punctuation recommended.
#'
#' @param temp Whether the the package should be detached and deleted at
#' the end of the R session. Set to `FALSE` to allow it to persist.
#'
#' @return
#' Returns `NULL` invisibly.
#' @export
dbp_init <- function(connection, package_name, temp = TRUE) {
  # Store connection
  # dbp_env[[paste0(package_name, "_connection")]] <- connection

  # Create temp package directory
  path <- create_db_package_path(package_name, temp)

  dbp_env[[paste0(package_name, "_path")]] <- path
  dbp_env[[paste0(package_name, "_is_temp")]] <- temp
  dbp_env[[paste0(package_name, "_connection")]] <- connection

  create_db_package_dir(path)
  create_db_package_desc(package_name, path)

  # Generate files in the temp_dir based on the connection
  # Each file should have a function and a roxygen docstring
  create_db_env_code(package_name, path, connection)

  # create_structure_code(package_name)
  # create_list_tables_code(package_name, path)
  # create_list_schema_code(package_name, path)
  # create_query_code(package_name, path)
  # create_execute_code(package_name, path)

  # A function per table to work with just that table (e.g. in dbplyr pipeline)
  # db_structure <- dbp_get_db_structure(connection)
  # mapply(create_table_funs, db_structure[["TABLE_SCHEMA"]] db_structure[["TABLE_NAME]],)

  invisible()
}

#' Load temp package
#'
#' @description Takes package files generated by [dbp_init()], generates the
#' Rd files for them using [roxygen2::roxygenise()], installs and loads the
#' package, attaching it to the search path with the package_name provided.
#'
#' @param package_name Name of a package already initialised with [dbp_init()].
#' Must be a valid R package name.
#'
#' @return
#' Returns `NULL` invisibly.
#' @export
dbp_load <- function(package_name, temp = TRUE) {
  path <- dbp_package_path(package_name)

  dbp_env[[paste0(package_name, "_path")]] <- path

  roxygen2::roxygenise(path)

  if (temp) {
    reg.finalizer(dbp_env, onexit = TRUE, function(e) {
      # Called when the dbp_env is unloaded
      # e.g. at the end of an R session
      remove_db_package(package_name)
    })
  }

  invisible()
}


#' Get the path for a dbpkgr package
#'
#' @description
#' #' Get the path for a package already created by
#' [dbp_package()] or [dbp_init()]
#'
#' @param package_name The name of the package to locate
#'
#' @return
#' A string path.
#' @export
dbp_package_path <- function(package_name) {
  var_name <- paste0(package_name, "_path")

  if (var_name %in% names(dbp_env)) {
    dbp_env[[var_name]]
  } else {
    stop(
      paste0(
        "dbpkgr could not find a path for ", package_name, "\n",
        "Check if the package has been created"
      )
    )
  }
}

#' Create package based on a database connection
#'
#' @description Generates a temp package with a number of functions
#' for interacting with a database connection.
#'
#' @param connection
#' A database connection object.
#'
#' @param package_name
#' A string to be used as the name of the temp package and the prefix to its
#' functions. Must be a valid package name; lowercase no punctuation recommended.
#'
#' @param temp Whether the the package should be detached and deleted at
#' the end of the R session. Set to `FALSE` to allow it to persist.
#'
#' @return
#' Returns `NULL` invisbly.
#' @export
#'
#' @examples
#' \dontrun{
#' # demo db in memory
#' con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
#' DBI::dbWriteTable(con, "mtcars", mtcars)
#'
#' dbp_package(con, "mydb")
#'
#' mydb_list_tables()
#' }
dbp_package <- function(connection, package_name, temp = TRUE) {
  dbp_init(connection, package_name, temp)

  dbp_load(package_name)

  invisible()
}
