dbp_env <- new.env(parent = emptyenv())

#' Prepare package files based on a database connection
#'
#' @description
#' Creates a folder under dbpkgr/, writing functions and roxygen docstrings.
#' Intended to be ready to be turned into a package with [dbp_load()].
#'
#' [dbp_package()] is the one-line way to get a package as the connection
#' interface up and running. However, as the automatically generated
#' documentation is quite limited, [dbp_init()] is provided to generate the
#' files without installing the package. Then you can make your own changes
#' to the package like adding more detailed roxygen documentation.
#' Once you're done,
#' you can pass the package name to [dbp_load()] to install and load
#' the package.
#'
#' @param connection
#' A database connection object.
#'
#' @param package_name
#' A string to be used as the name of the temporary package and the prefix to its
#' functions. Must be a valid package name; lowercase no punctuation recommended.
#'
#' @return
#' Returns `NULL` invisibly.
#' @export
dbp_init <- function(connection, package_name) {
  # Store connection
  assign(paste0(package_name, "_connection"), connection, envir = dbp_env)

  # Create temporary package directory
  path <- dbp_package_path(package_name)

  create_temp_package_dir(path)
  create_temp_package_desc(package_name, path)

  # Generate files in the temp_dir based on the connection
  # Each file should have a function and a auto-generated roxygen docstring
  # The functions should be options:

  # create_list_tables_fun(package_name, path)
  # create_list_schema_fun(package_name, path)
  # create_query_fun(package_name, path)
  # create_execute_fun(package_name, path)
  # Execute (SQL) on the connection

  # A function per table to work with just that table (e.g. in dbplyr pipeline)
  # db_structure <- dbp_get_db_structure(connection)

  # mapply(create_table_funs, db_structure[["TABLE_SCHEMA"]] db_structure[["TABLE_NAME]],)

  invisible()
}

#' Load temporary package
#'
#' @description Takes package files generated by [dbp_init()], generates the
#' Rd files for them using [roxygen2::roxygenise()], installs and loads the
#' package, attaching it to the search path with the package_name provided.
#'
#' @param package_name Name of a package already initialised with [dbp_init()].
#' Must be a valid R package name.
#'
#' @return
#' Returns `NULL` invisibly.
#' @export
dbp_load <- function(package_name) {
  path <- dbp_package_path(package_name)

  # Generate man/ folder and Rd files
  create_temp_package_man(path)

  utils::install.packages(path, repos = NULL, type = "source")

  library(package_name, character.only = TRUE)

  invisible()
}

dbp_package_path <- function(package_name) {
  file.path("dbpkgr", package_name)
}

#' Create package based on a database connection
#'
#' @description Generates a temporary package
#'
#' @param connection
#' A database connection object.
#'
#' @param package_name
#' A string to be used as the name of the temporary package and the prefix to its
#' functions. Must be a valid package name; lowercase no punctuation recommended.
#'
#' @return
#' Returns `NULL` invisbly.
#' @export
dbp_package <- function(connection, package_name) {
  # if package not initialised (check dbp_env?):
  dbp_init(connection, package_name)

  dbp_load(package_name)

  invisible()
}
